[project]
name = "cloud-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-aiplatform>=1.107.0",
    "google-genai>=1.29.0",
]
